all: practica2 practica2Hilos
practica2: practica2.c
	gcc -o practica2 practica2.c -lm
practica2Hilos: practica2Hilos.c
	gcc -o practica2Hilos practica2Hilos.c -lpthread -lm
clean: 
	rm practica2 practica2Hilos