all: practica4 practica4_ejemplo
practica4: practica4.c
	gcc -o practica4 practica4.c -lm
practica4_ejemplo: practica4_ejemplo.c
	gcc -o practica4_ejemplo practica4_ejemplo.c -lm
clean: 
	rm practica1 practica1Hilos