all: practica1 practica1Hilos
practica1: practica1.c
	gcc -o practica1 practica1.c -lm
practica1Hilos: practica1Hilos.c
	gcc -o practica1Hilos practica1Hilos.c -lpthread -lm
clean: 
	rm practica1 practica1Hilos